"""add forecast signal alert tables

Revision ID: df8cb4e4d1b2
Revises: 18c3bf0ed806
Create Date: 2026-03-23 22:03:53.085372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df8cb4e4d1b2'
down_revision: Union[str, Sequence[str], None] = '18c3bf0ed806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_configs_id'), 'alert_configs', ['id'], unique=False)
    
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('horizon_weeks', sa.Integer(), nullable=False),
    sa.Column('predicted_qty', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=False),
    sa.Column('upper_bound', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('signal_contributions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_override', sa.Boolean(), nullable=True),
    sa.Column('override_qty', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_id'), 'forecasts', ['id'], unique=False)
    
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('signal_name', sa.String(length=100), nullable=False),
    sa.Column('signal_value', sa.Float(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    
    op.create_table('alert_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['alert_configs.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_history_id'), 'alert_history', ['id'], unique=False)
    
    op.add_column('products', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('unit', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_unique_constraint(None, 'products', ['sku'])
    
    # FIX: Added server_default="0" so existing rows have a value for the NOT NULL constraint
    op.add_column('sales_history', sa.Column('revenue', sa.Integer(), server_default="0", nullable=False))
    op.add_column('sales_history', sa.Column('created_at', sa.DateTime(), nullable=True))
    
    # FIX: Added server_default so existing rows can be part of the unique constraint
    op.add_column('sales_history', sa.Column('channel', sa.String(length=50), server_default="direct", nullable=True))
    
    op.create_unique_constraint('unique_sales_entry', 'sales_history', ['product_id', 'date', 'channel'])
    # ### end Alembic commands ###
