"""add_model_registry

Revision ID: f1d9dc14af4f
Revises: df8cb4e4d1b2
Create Date: 2026-04-05 16:02:34.880729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1d9dc14af4f'
down_revision: Union[str, Sequence[str], None] = 'df8cb4e4d1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_registry_id'), 'model_registry', ['id'], unique=False)
    op.alter_column('sales_history', 'revenue',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Numeric(precision=12, scale=2),
               nullable=True)
    op.alter_column('sales_history', 'channel',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_history', 'channel',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'direct'::character varying"),
               existing_nullable=True)
    op.alter_column('sales_history', 'revenue',
               existing_type=sa.Numeric(precision=12, scale=2),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_model_registry_id'), table_name='model_registry')
    op.drop_table('model_registry')
    # ### end Alembic commands ###
